In [21]:
#数据加载
import pandas as pd

df = pd.read_csv('./car_complain.csv')
df
#print(df)
#df.to_excel('./car_complain.xlsx', index=False)
#导出为excel后缀应为.xlsx，False首字母需大写

#df = df.drop('problem', axis=1).join(df.problem.str.get_dummies(','))
#print(df)

,id,brand,car_model,type,desc,problem,datetime,status
0,482028,一汽马自达,阿特兹,2020款 2.5L 蓝天运动版,一汽马自达阿特兹B柱异响 车内异响严重,"H93,H15,",2020-06-08,信息审核
1,482027,江淮汽车,江淮iEV6E,2017款 iEV6E,江淮iEV6E动力电池故障 无法充电,"H343,",2020-06-08,信息审核
2,482026,一汽马自达,阿特兹,2020款 2.5L 蓝天运动版,一汽马自达阿特兹车身异响 天窗异响,"H93,H15,H89,",2020-06-08,信息审核
3,482022,一汽-大众,迈腾,2009款 1.8TSI DSG 舒适型,一汽大众迈腾起步和刹车时车辆抖动\t,"B84,E111,",2020-06-08,信息审核
4,482019,众泰汽车,众泰T600 Coupe,2017款 1.5T 自动 尊享型,众泰T600 Coupe售后维修配件一直缺货,"N318,",2020-06-08,厂家受理
...,...,...,...,...,...,...,...,...
595,480802,北京现代,领动,2016款 1.6L 自动 智炫·精英型,北京现代领动ABS和防侧滑故障灯同时亮\t,"E62,H170,I295,I294,",2020-06-05,信息审核
596,480801,一汽-大众,高尔夫,2016款 1.4TSI 25周年纪念版,一汽大众高尔夫仪表提示变速箱挂入P挡,"B96,",2020-06-05,处理反馈
597,480799,吉利汽车,星越,2020款 350T 魅影骑士版AWD,吉利星越车机系统虚假宣传 卡顿严重,"H155,M279,",2020-06-05,用户评分
598,480798,北京现代,悦纳,2016款 1.4L 手动 炫酷版 GLS,北京现代悦纳发动机曲轴螺丝断裂,"A145,",2020-06-05,信息审核
599,480795,东风日产,逍客,2016款 2.0L CVT 精英版,东风日产逍客变速箱报故障码P17F1,"B84,",2020-06-05,处理反馈

In [22]:
# 0代表没有，1代表存在
df = df.drop('problem', axis=1).join(df.problem.str.get_dummies(','))
df

,id,brand,car_model,type,desc,datetime,status,A11,A114,A12,...,N318,N319,O296,O326,O348,O354,Q322,Q323,Q349,Q350
0,482028,一汽马自达,阿特兹,2020款 2.5L 蓝天运动版,一汽马自达阿特兹B柱异响 车内异响严重,2020-06-08,信息审核,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,482027,江淮汽车,江淮iEV6E,2017款 iEV6E,江淮iEV6E动力电池故障 无法充电,2020-06-08,信息审核,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,482026,一汽马自达,阿特兹,2020款 2.5L 蓝天运动版,一汽马自达阿特兹车身异响 天窗异响,2020-06-08,信息审核,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,482022,一汽-大众,迈腾,2009款 1.8TSI DSG 舒适型,一汽大众迈腾起步和刹车时车辆抖动\t,2020-06-08,信息审核,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,482019,众泰汽车,众泰T600 Coupe,2017款 1.5T 自动 尊享型,众泰T600 Coupe售后维修配件一直缺货,2020-06-08,厂家受理,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,480802,北京现代,领动,2016款 1.6L 自动 智炫·精英型,北京现代领动ABS和防侧滑故障灯同时亮\t,2020-06-05,信息审核,0,0,0,...,0,0,0,0,0,0,0,0,0,0
596,480801,一汽-大众,高尔夫,2016款 1.4TSI 25周年纪念版,一汽大众高尔夫仪表提示变速箱挂入P挡,2020-06-05,处理反馈,0,0,0,...,0,0,0,0,0,0,0,0,0,0
597,480799,吉利汽车,星越,2020款 350T 魅影骑士版AWD,吉利星越车机系统虚假宣传 卡顿严重,2020-06-05,用户评分,0,0,0,...,0,0,0,0,0,0,0,0,0,0
598,480798,北京现代,悦纳,2016款 1.4L 手动 炫酷版 GLS,北京现代悦纳发动机曲轴螺丝断裂,2020-06-05,信息审核,0,0,0,...,0,0,0,0,0,0,0,0,0,0
599,480795,东风日产,逍客,2016款 2.0L CVT 精英版,东风日产逍客变速箱报故障码P17F1,2020-06-05,处理反馈,0,0,0,...,0,0,0,0,0,0,0,0,0,0

按照brand统计 投诉总数，不同problem类型的总数<br>
按照投诉总数进行排序<br>
按照指定的problem类型进行排序

In [23]:
#数据清洗，将别名合并
#替换函数f(x)
def f(x):
    x = x.replace('一汽-大众','一汽大众')
    return x

df['brand'] = df['brand'].apply(f)

#聚合，以brand分组，聚合id数量
result = df.groupby(['brand'])['id'].agg(['count'])
result

        count
brand
一汽丰田       12
一汽吉林        2
一汽大众       58
一汽大众奥迪     19
一汽奔腾        6
...       ...
长安汽车        6
长安铃木        2
长安马自达       4
雷克萨斯        2
领克汽车        5

[74 rows x 1 columns]

In [24]:
#标签从0，1，2，……，7第七个A11开始
tags = df.columns[7:]
tags

Index(['A11', 'A114', 'A12', 'A13', 'A136', 'A14', 'A145', 'A163', 'A174',
       'A18',
       ...
       'N318', 'N319', 'O296', 'O326', 'O348', 'O354', 'Q322', 'Q323', 'Q349',
       'Q350'],
      dtype='object', length=174)

In [25]:
result2 = df.groupby(['brand'])[tags].agg(['sum'])
result2

,A11,A114,A12,A13,A136,A14,A145,A163,A174,A18,...,N318,N319,O296,O326,O348,O354,Q322,Q323,Q349,Q350
,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,...,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum
brand,,,,,,,,,,,,,,,,,,,,,
一汽丰田,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
一汽吉林,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
一汽大众,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,1,0,0,0,0
一汽大众奥迪,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
一汽奔腾,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
长安汽车,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
长安铃木,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
长安马自达,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
雷克萨斯,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
领克汽车,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [26]:
result2 = result.merge(result2, left_index=True, right_index=True, how='left')
result2

D:\Users\HuYunlin\Anaconda3\lib\site-packages\pandas\core\reshape\merge.py:618: UserWarning: merging between different levels can give an unintended result (1 levels on the left, 2 on the right)
  warnings.warn(msg, UserWarning)

,count,"(A11, sum)","(A114, sum)","(A12, sum)","(A13, sum)","(A136, sum)","(A14, sum)","(A145, sum)","(A163, sum)","(A174, sum)",...,"(N318, sum)","(N319, sum)","(O296, sum)","(O326, sum)","(O348, sum)","(O354, sum)","(Q322, sum)","(Q323, sum)","(Q349, sum)","(Q350, sum)"
brand,,,,,,,,,,,,,,,,,,,,,
一汽丰田,12,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
一汽吉林,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
一汽大众,58,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
一汽大众奥迪,19,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
一汽奔腾,6,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
长安汽车,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
长安铃木,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
长安马自达,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
雷克萨斯,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
领克汽车,5,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [28]:
#brand目前为索引列，将brand复原为正常列，reset索引列
result2.reset_index(inplace=True)
result2

,brand,count,"(A11, sum)","(A114, sum)","(A12, sum)","(A13, sum)","(A136, sum)","(A14, sum)","(A145, sum)","(A163, sum)",...,"(N318, sum)","(N319, sum)","(O296, sum)","(O326, sum)","(O348, sum)","(O354, sum)","(Q322, sum)","(Q323, sum)","(Q349, sum)","(Q350, sum)"
0,一汽丰田,12,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,一汽吉林,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,一汽大众,58,0,0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
3,一汽大众奥迪,19,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,一汽奔腾,6,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,长安汽车,6,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
70,长安铃木,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
71,长安马自达,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
72,雷克萨斯,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
73,领克汽车,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [29]:
result2.to_csv("./result.csv")

In [32]:
#按照count，从大到小进行排序
result2 = result2.sort_values('count', ascending=False)
result2

,brand,count,"(A11, sum)","(A114, sum)","(A12, sum)","(A13, sum)","(A136, sum)","(A14, sum)","(A145, sum)","(A163, sum)",...,"(N318, sum)","(N319, sum)","(O296, sum)","(O326, sum)","(O348, sum)","(O354, sum)","(Q322, sum)","(Q323, sum)","(Q349, sum)","(Q350, sum)"
37,吉利汽车,96,0,0,1,0,0,1,0,0,...,0,0,0,0,7,0,0,0,0,1
7,一汽马自达,95,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,一汽大众,58,0,0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
8,上汽大众,36,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,一汽大众奥迪,19,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,天津一汽,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,多士星,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,北汽新能源,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,北汽昌河,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
14,东风小康,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
result2.to_csv("./result.csv")

In [35]:
#查询按(O348, sum)排序
query = ('O348', 'sum')
result2.sort_values(query, ascending=False)

,brand,count,"(A11, sum)","(A114, sum)","(A12, sum)","(A13, sum)","(A136, sum)","(A14, sum)","(A145, sum)","(A163, sum)",...,"(N318, sum)","(N319, sum)","(O296, sum)","(O326, sum)","(O348, sum)","(O354, sum)","(Q322, sum)","(Q323, sum)","(Q349, sum)","(Q350, sum)"
37,吉利汽车,96,0,0,1,0,0,1,0,0,...,0,0,0,0,7,0,0,0,0,1
43,奇瑞汽车,14,0,0,0,0,0,0,0,0,...,0,0,0,1,2,0,0,0,1,0
29,北京现代,18,0,0,0,0,1,1,1,3,...,0,0,0,0,1,0,0,2,0,0
1,一汽吉林,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
66,观致汽车,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36,吉利新能源,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
71,长安马自达,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,华晨宝马,5,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
73,领克汽车,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,东风小康,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [37]:
result2.to_csv("./result_O348.csv")